### ISSUE TITLE
Report issues to implementers and create issue tracking UI

### ISSUE THREAD

**Issue by inikulin** [inikulin/cookie-compat#2]
- [x] Chrome (https://bugs.chromium.org/p/chromium/issues/detail?id=601786) (**fixed**)
- [x] Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=1255938)
- [ ] Safari
- [x] IE, Edge (https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7151935/)
